//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neurona
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARACTERS
    {
        public int ID { get; set; }
        public string IN_CARACTER { get; set; }
        public string OUT_CARACTER { get; set; }
        public string CARACTER { get; set; }
    }
}
