//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neurona
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARACTER
    {
        public int ID { get; set; }
        public string IN_CARACTER { get; set; }
        public string OUT_CARACTER { get; set; }
        public string CARACTER1 { get; set; }
    }
}
